name: Deploy Code

on:
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Test step"
        run: |
          echo "Clone Repo"
          echo "${{ toJson(github) }}"
          git clone https://github.com/${{ github.repository }}.git
