name: Deploy Code

on:
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allows pushing to the repo
      actions: read    # Allows running actions
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
#        with:
#          token: ${{ secrets.Token }}

      - name: "Test step"
        run: |
          echo "Clone Repo"
          echo "${{ toJson(github) }}"
          git clone https://github.com/${{ github.repository }}.git
